### ISSUE TITLE
Problem with finding module

### ISSUE THREAD

**Issue by baptiste-g-etu** [TomerADev/imgflip#5]
Hello, i work for a protect with imgflip api in a website, i use browserify for use require('imgflip') but it can find the module
Error: Cannot find module 'imgflip' from

Can you help me please?

**Comment by TomerAberbach** [comment]
This module is server-side only so I don't think it's possible to use with browserify. Correct me if I'm wrong, but browserify is used to bundle code to run in the browser right?

For what it's worth, the reason I'm not supporting this is because there's no way to securely do it. The Imgflip API requires you to provide a username and password. If you exposed that on the client-side, then any website visitor would be able to log into the account by viewing the JavaScript source code.

I would recommend setting up an endpoint on a server (you could use a serverless function too) that uses this module.

**Comment by baptiste-g-etu** [comment]
ok, thanks
